  - name: copying mongodb repo to /etc/yum.repos.d/mongo.repo   
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: copy catalogue js
    ansible.builtin.copy:
      src: catalogue.js
      dest: /tmp/catalogue.js
    
  - name: installing mongodb
    ansible.builtin.yum:
      name: mongodb-org 
      state: installed      
      
  - name: enabling and staring mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: establishing connection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restarting mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted

  - name: load catalogue data
    ansible.builtin.command: mongo --host localhost < /tmp/catalogue.js


